// Demo data for development and showcasing
// All data is fictional and for demonstration purposes only

import type {
  User,
  Project,
  Transaction,
  Notification,
  Activity,
} from "@/types"

export type {
  User,
  Project,
  Transaction,
  Notification,
  Activity,
  UserRole,
  UserStatus,
  ProjectStatus,
  TransactionStatus,
  PaymentMethod,
  NotificationType,
} from "@/types"

// Users
export const demoUsers: User[] = [
  {
    id: "usr_1",
    name: "Ethan Caldwell",
    email: "ethan.caldwell@acmecorp.io",
    role: "owner",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    lastActiveAt: "2026-10-02T10:23:00Z",
  },
  {
    id: "usr_2",
    name: "Priya Sharma",
    email: "priya.sharma@acmecorp.io",
    role: "admin",
    status: "active",
    createdAt: "2024-02-10T09:00:00Z",
    lastActiveAt: "2026-10-02T09:45:00Z",
  },
  {
    id: "usr_3",
    name: "Marcus Webb",
    email: "marcus.webb@acmecorp.io",
    role: "member",
    status: "active",
    createdAt: "2024-03-05T11:00:00Z",
    lastActiveAt: "2026-10-01T16:10:00Z",
  },
  {
    id: "usr_4",
    name: "Lena Fischer",
    email: "lena.fischer@acmecorp.io",
    role: "member",
    status: "active",
    createdAt: "2024-04-20T14:00:00Z",
    lastActiveAt: "2026-10-02T08:30:00Z",
  },
  {
    id: "usr_5",
    name: "Carlos Mendez",
    email: "carlos.mendez@acmecorp.io",
    role: "viewer",
    status: "invited",
    createdAt: "2026-09-28T10:00:00Z",
    lastActiveAt: "2026-09-28T10:00:00Z",
  },
  {
    id: "usr_6",
    name: "Aisha Okonkwo",
    email: "aisha.okonkwo@acmecorp.io",
    role: "member",
    status: "active",
    createdAt: "2024-05-12T12:00:00Z",
    lastActiveAt: "2026-09-30T14:20:00Z",
  },
  {
    id: "usr_7",
    name: "James Thornton",
    email: "james.thornton@acmecorp.io",
    role: "admin",
    status: "inactive",
    createdAt: "2024-01-28T08:00:00Z",
    lastActiveAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "usr_8",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@acmecorp.io",
    role: "member",
    status: "active",
    createdAt: "2024-06-18T13:00:00Z",
    lastActiveAt: "2026-10-02T11:15:00Z",
  },
  {
    id: "usr_9",
    name: "Sofia Rossi",
    email: "sofia.rossi@acmecorp.io",
    role: "member",
    status: "suspended",
    createdAt: "2024-03-22T09:00:00Z",
    lastActiveAt: "2026-07-20T15:00:00Z",
  },
  {
    id: "usr_10",
    name: "Noah Petersen",
    email: "noah.petersen@acmecorp.io",
    role: "viewer",
    status: "active",
    createdAt: "2024-07-07T10:00:00Z",
    lastActiveAt: "2026-10-01T12:00:00Z",
  },
]

// Projects
export const demoProjects: Project[] = [
  {
    id: "prj_1",
    name: "Platform Redesign",
    description: "Redesigning the core platform UI with the new design system",
    status: "active",
    progress: 68,
    members: 5,
    owner: "Ethan Caldwell",
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z",
    dueDate: "2026-12-31T00:00:00Z",
  },
  {
    id: "prj_2",
    name: "API Gateway Migration",
    description: "Migrating legacy APIs to the new GraphQL gateway",
    status: "active",
    progress: 42,
    members: 3,
    owner: "Priya Sharma",
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-10-01T16:00:00Z",
    dueDate: "2026-11-15T00:00:00Z",
  },
  {
    id: "prj_3",
    name: "Mobile App MVP",
    description: "Building the first version of the mobile app for iOS and Android",
    status: "active",
    progress: 25,
    members: 4,
    owner: "Marcus Webb",
    createdAt: "2026-07-01T08:00:00Z",
    updatedAt: "2026-09-30T14:00:00Z",
    dueDate: "2027-03-01T00:00:00Z",
  },
  {
    id: "prj_4",
    name: "Data Analytics Pipeline",
    description: "Setting up real-time analytics pipeline with Kafka and ClickHouse",
    status: "paused",
    progress: 55,
    members: 2,
    owner: "Lena Fischer",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-08-01T09:00:00Z",
    dueDate: "2026-10-30T00:00:00Z",
  },
  {
    id: "prj_5",
    name: "Security Audit 2026",
    description: "Comprehensive security audit and penetration testing",
    status: "completed",
    progress: 100,
    members: 3,
    owner: "Ethan Caldwell",
    createdAt: "2026-01-01T08:00:00Z",
    updatedAt: "2026-09-15T16:00:00Z",
  },
  {
    id: "prj_6",
    name: "Customer Portal",
    description: "Self-service customer portal for account management",
    status: "active",
    progress: 78,
    members: 6,
    owner: "Aisha Okonkwo",
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-10-02T09:00:00Z",
    dueDate: "2026-11-30T00:00:00Z",
  },
]

// Transactions
export const demoTransactions: Transaction[] = [
  {
    id: "txn_1",
    description: "Pro Plan - Monthly",
    amount: 29.0,
    status: "completed",
    date: "2026-10-01T12:00:00Z",
    customer: "Acme Corp",
    method: "card",
  },
  {
    id: "txn_2",
    description: "Enterprise Add-on",
    amount: 149.0,
    status: "completed",
    date: "2026-09-28T10:30:00Z",
    customer: "TechFlow Inc",
    method: "bank",
  },
  {
    id: "txn_3",
    description: "Pro Plan - Monthly",
    amount: 29.0,
    status: "pending",
    date: "2026-10-02T08:00:00Z",
    customer: "StartupLab",
    method: "paypal",
  },
  {
    id: "txn_4",
    description: "Seat Expansion (5 seats)",
    amount: 75.0,
    status: "completed",
    date: "2026-09-25T14:20:00Z",
    customer: "DevHouse Agency",
    method: "card",
  },
  {
    id: "txn_5",
    description: "Pro Plan - Monthly",
    amount: 29.0,
    status: "failed",
    date: "2026-09-20T09:00:00Z",
    customer: "ByteCraft",
    method: "card",
  },
  {
    id: "txn_6",
    description: "Pro Plan - Refund",
    amount: -29.0,
    status: "refunded",
    date: "2026-09-22T11:00:00Z",
    customer: "CodeNest",
    method: "card",
  },
]

// Notifications
export const demoNotifications: Notification[] = [
  {
    id: "ntf_1",
    title: "New user registered",
    description: "Carlos Mendez signed up and is awaiting approval.",
    type: "info",
    read: false,
    createdAt: "2026-10-02T10:15:00Z",
    href: "/users",
  },
  {
    id: "ntf_2",
    title: "Payment received",
    description: "Enterprise Add-on payment of $149 from TechFlow Inc confirmed.",
    type: "success",
    read: false,
    createdAt: "2026-10-01T14:30:00Z",
    href: "/settings/billing",
  },
  {
    id: "ntf_3",
    title: "Deployment completed",
    description: "Platform Redesign v2.4.1 deployed to production successfully.",
    type: "success",
    read: false,
    createdAt: "2026-09-30T18:00:00Z",
  },
  {
    id: "ntf_4",
    title: "Payment failed",
    description: "Failed to charge ByteCraft for the Pro Plan. Action required.",
    type: "error",
    read: true,
    createdAt: "2026-09-20T09:05:00Z",
    href: "/settings/billing",
  },
  {
    id: "ntf_5",
    title: "Storage limit approaching",
    description: "You've used 85% of your storage quota. Consider upgrading.",
    type: "warning",
    read: true,
    createdAt: "2026-09-18T12:00:00Z",
    href: "/settings/billing",
  },
]

// Activity
export const demoActivity: Activity[] = [
  {
    id: "act_1",
    actor: { name: "Ethan Caldwell" },
    action: "updated",
    resource: "project",
    resourceId: "prj_1",
    timestamp: "2026-10-02T10:23:00Z",
    metadata: { project: "Platform Redesign", field: "status" },
  },
  {
    id: "act_2",
    actor: { name: "Priya Sharma" },
    action: "invited",
    resource: "user",
    resourceId: "usr_5",
    timestamp: "2026-10-02T09:45:00Z",
    metadata: { user: "Carlos Mendez", role: "viewer" },
  },
  {
    id: "act_3",
    actor: { name: "Aisha Okonkwo" },
    action: "created",
    resource: "project",
    resourceId: "prj_6",
    timestamp: "2026-10-01T16:10:00Z",
    metadata: { project: "Customer Portal" },
  },
  {
    id: "act_4",
    actor: { name: "Lena Fischer" },
    action: "updated",
    resource: "project",
    resourceId: "prj_4",
    timestamp: "2026-10-01T14:00:00Z",
    metadata: { project: "Data Analytics Pipeline", field: "status", value: "paused" },
  },
  {
    id: "act_5",
    actor: { name: "Ethan Caldwell" },
    action: "changed role",
    resource: "user",
    resourceId: "usr_7",
    timestamp: "2026-09-30T11:00:00Z",
    metadata: { user: "James Thornton", from: "member", to: "admin" },
  },
]

// Analytics chart data
export const revenueData = [
  { month: "Apr", revenue: 18400, users: 310 },
  { month: "May", revenue: 22100, users: 378 },
  { month: "Jun", revenue: 19800, users: 342 },
  { month: "Jul", revenue: 26500, users: 415 },
  { month: "Aug", revenue: 31200, users: 490 },
  { month: "Sep", revenue: 28700, users: 462 },
  { month: "Oct", revenue: 34100, users: 521 },
]

export const projectStatusData = [
  { name: "Active", value: 4, fill: "var(--chart-1)" },
  { name: "Paused", value: 1, fill: "var(--chart-2)" },
  { name: "Completed", value: 1, fill: "var(--chart-3)" },
]

export const userRoleData = [
  { role: "Owner", count: 1 },
  { role: "Admin", count: 2 },
  { role: "Member", count: 6 },
  { role: "Viewer", count: 2 },
]
